package com.example.common.domain.models

import androidx.annotation.DrawableRes
import com.example.common.R

enum class CategoryIcon(
    @DrawableRes override val drawableRes: Int
) : Icon {
    Apartment(R.drawable.ic_apartment),
    Bank(R.drawable.ic_bank),
    Basket(R.drawable.ic_basket),
    Beach(R.drawable.ic_beach),
    Beer(R.drawable.ic_beer),
    Book(R.drawable.ic_book),
    Build(R.drawable.ic_build),
    Bulb(R.drawable.ic_bulb),
    Bus(R.drawable.ic_bus),
    Cake(R.drawable.ic_cake),
    Call(R.drawable.ic_call),
    Car(R.drawable.ic_car),
    Card(R.drawable.ic_card),
    Cardiology(R.drawable.ic_cardiology),
    Cart(R.drawable.ic_cart),
    Chair(R.drawable.ic_chair),
    Checkroom(R.drawable.ic_checkroom),
    Controller(R.drawable.ic_controller),
    Crib(R.drawable.ic_crib),
    Cut(R.drawable.ic_cut),
    Devices(R.drawable.ic_devices),
    Diamond(R.drawable.ic_diamond),
    Electric(R.drawable.ic_electric),
    Empty(R.drawable.ic_empty),
    Family(R.drawable.ic_family),
    Fastfood(R.drawable.ic_fastfood),
    Fitness(R.drawable.ic_fitness),
    Flight(R.drawable.ic_flight),
    Flower(R.drawable.ic_flower),
    Garden(R.drawable.ic_garden),
    Gas(R.drawable.ic_gas),
    Gavel(R.drawable.ic_gavel),
    Gift(R.drawable.ic_gift),
    Heart(R.drawable.ic_heart),
    Hiking(R.drawable.ic_hiking),
    House(R.drawable.ic_house),
    Interests(R.drawable.ic_interests),
    Love(R.drawable.ic_love),
    Meditation(R.drawable.ic_meditation),
    Monetization(R.drawable.ic_monetization),
    Monitoring(R.drawable.ic_monitoring),
    Mood(R.drawable.ic_mood),
    Motorcycle(R.drawable.ic_motorcycle),
    Newspaper(R.drawable.ic_newspaper),
    Nightlife(R.drawable.ic_nightlife),
    Payments(R.drawable.ic_payments),
    Pets(R.drawable.ic_pets),
    Phone(R.drawable.ic_phone),
    Photo(R.drawable.ic_photo),
    Plant(R.drawable.ic_plant),
    Repair(R.drawable.ic_repair),
    Restaurant(R.drawable.ic_restaurant),
    Savings(R.drawable.ic_savings),
    School(R.drawable.ic_school),
    Science(R.drawable.ic_science),
    Selfcare(R.drawable.ic_selfcare),
    Ship(R.drawable.ic_ship),
    Shopping(R.drawable.ic_shopping),
    Smoking(R.drawable.ic_smoking),
    Sport(R.drawable.ic_sport),
    Store(R.drawable.ic_store),
    Subway(R.drawable.ic_subway),
    Taxi(R.drawable.ic_taxi),
    Tea(R.drawable.ic_tea),
    Thermostat(R.drawable.ic_thermostat),
    Tree(R.drawable.ic_tree),
    Tv(R.drawable.ic_tv),
    Volunteer(R.drawable.ic_volunteer),
    Wallet(R.drawable.ic_wallet),
    Web(R.drawable.ic_web),
    Wifi(R.drawable.ic_wifi),
    Wine(R.drawable.ic_wine),
    Wire(R.drawable.ic_wire),
    Work(R.drawable.ic_work),
}